services:
  app:
    build: .
    container_name: node_app
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - ${DATABASE_HOST}
      - ${REDIS_HOST}
    volumes:
      - ./:/app
    command: npm run dev

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/
      
  redis:
    image: redis:7
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  postgres_data: